"""Type stubs for exp (expression filter) module."""

# Expression type constants
EXP_TYPE_NIL: int
EXP_TYPE_BOOL: int
EXP_TYPE_INT: int
EXP_TYPE_STRING: int
EXP_TYPE_LIST: int
EXP_TYPE_MAP: int
EXP_TYPE_BLOB: int
EXP_TYPE_FLOAT: int
EXP_TYPE_GEO: int
EXP_TYPE_HLL: int

# Value constructors
def int_val(val: int) -> dict: ...
def float_val(val: float) -> dict: ...
def string_val(val: str) -> dict: ...
def bool_val(val: bool) -> dict: ...
def blob_val(val: bytes) -> dict: ...
def list_val(val: list) -> dict: ...
def map_val(val: dict) -> dict: ...
def geo_val(val: str) -> dict: ...
def nil() -> dict: ...
def infinity() -> dict: ...
def wildcard() -> dict: ...

# Bin accessors
def int_bin(name: str) -> dict: ...
def float_bin(name: str) -> dict: ...
def string_bin(name: str) -> dict: ...
def bool_bin(name: str) -> dict: ...
def blob_bin(name: str) -> dict: ...
def list_bin(name: str) -> dict: ...
def map_bin(name: str) -> dict: ...
def geo_bin(name: str) -> dict: ...
def hll_bin(name: str) -> dict: ...
def bin_exists(name: str) -> dict: ...
def bin_type(name: str) -> dict: ...

# Record metadata
def key(exp_type: int) -> dict: ...
def key_exists() -> dict: ...
def set_name() -> dict: ...
def record_size() -> dict: ...
def last_update() -> dict: ...
def since_update() -> dict: ...
def void_time() -> dict: ...
def ttl() -> dict: ...
def is_tombstone() -> dict: ...
def digest_modulo(modulo: int) -> dict: ...

# Comparison operations
def eq(left: dict, right: dict) -> dict: ...
def ne(left: dict, right: dict) -> dict: ...
def gt(left: dict, right: dict) -> dict: ...
def ge(left: dict, right: dict) -> dict: ...
def lt(left: dict, right: dict) -> dict: ...
def le(left: dict, right: dict) -> dict: ...

# Logical operations
def and_(*exprs: dict) -> dict: ...
def or_(*exprs: dict) -> dict: ...
def not_(expr: dict) -> dict: ...
def xor_(*exprs: dict) -> dict: ...

# Numeric operations
def num_add(*exprs: dict) -> dict: ...
def num_sub(*exprs: dict) -> dict: ...
def num_mul(*exprs: dict) -> dict: ...
def num_div(*exprs: dict) -> dict: ...
def num_mod(numerator: dict, denominator: dict) -> dict: ...
def num_pow(base: dict, exponent: dict) -> dict: ...
def num_log(num: dict, base: dict) -> dict: ...
def num_abs(value: dict) -> dict: ...
def num_floor(num: dict) -> dict: ...
def num_ceil(num: dict) -> dict: ...
def to_int(num: dict) -> dict: ...
def to_float(num: dict) -> dict: ...
def min_(*exprs: dict) -> dict: ...
def max_(*exprs: dict) -> dict: ...

# Integer bitwise operations
def int_and(*exprs: dict) -> dict: ...
def int_or(*exprs: dict) -> dict: ...
def int_xor(*exprs: dict) -> dict: ...
def int_not(expr: dict) -> dict: ...
def int_lshift(value: dict, shift: dict) -> dict: ...
def int_rshift(value: dict, shift: dict) -> dict: ...
def int_arshift(value: dict, shift: dict) -> dict: ...
def int_count(expr: dict) -> dict: ...
def int_lscan(value: dict, search: dict) -> dict: ...
def int_rscan(value: dict, search: dict) -> dict: ...

# Pattern matching
def regex_compare(regex: str, flags: int, bin_expr: dict) -> dict: ...
def geo_compare(left: dict, right: dict) -> dict: ...

# Variables and control flow
def cond(*exprs: dict) -> dict: ...
def var(name: str) -> dict: ...
def def_(name: str, value: dict) -> dict: ...
def let_(*exprs: dict) -> dict: ...
