"""Type stubs for aerospike_py.predicates module."""

from typing import Any

def equals(bin_name: str, val: Any) -> tuple[str, str, Any]: ...
def between(bin_name: str, min_val: Any, max_val: Any) -> tuple[str, str, Any, Any]: ...
def contains(bin_name: str, index_type: int, val: Any) -> tuple[str, str, int, Any]: ...
def geo_within_geojson_region(bin_name: str, geojson: str) -> tuple[str, str, str]: ...
def geo_within_radius(bin_name: str, lat: float, lng: float, radius: float) -> tuple[str, str, float, float, float]: ...
def geo_contains_geojson_point(bin_name: str, geojson: str) -> tuple[str, str, str]: ...
