apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aerospike-benchmark
  namespace: monitoring
  labels:
    app: aerospike-benchmark
spec:
  namespaceSelector:
    matchNames:
      - mona-adagent
  selector:
    matchLabels:
      app: aerospike-benchmark
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
